"""Drive the MATLAB `pitzer_mix` and capture every intermediate the parity spec compares.

Spec: pitzer-parity-test-cases.md sec.1. The MATLAB is the oracle; this module is the
only thing that runs it.

How the oracle is exposed without editing the original (spec sec.1):
`pitzer-kim functions.m` is copied to `_generated/pitzer_body.m` with two lines removed
— the `function` declaration and the trailing `end`. It becomes a script, so every local
lands in the caller's workspace and is readable by name. The copy is regenerated from the
original on every run, so it cannot drift.

Two interchangeable backends:

    oct2py   GNU Octave in-process (default). Needs the `octave-cli` binary.
    matlab   `matlab -batch` subprocess. The oracle the spec actually names.

They agree with each other to <= 1.4e-11 for X >= 0.2 — comfortably inside the spec's
1e-8 tier — and diverge only below X ~ 0.05, which is the I < 0.01 regime where the spec
already allows 1e-4. Either is a valid oracle at these tolerances; running both is a useful
cross-check, because a Python mismatch in a range where they agree is unambiguously ours.

Results are cached to `oracle_octave.csv` / `oracle_matlab.csv`, which are committed, so
the pytest suite runs with neither Octave nor MATLAB installed.

    python utils/pitzer_parity/oracle.py --regenerate
    python utils/pitzer_parity/oracle.py --regenerate --backend matlab
    python utils/pitzer_parity/oracle.py --cross-check
"""

import argparse
import logging
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np

import cases
from cases import TERM_NAMES

# NOTE: deliberately does NOT import utils.pitzer. oct2py forks a pty to talk to Octave, and
# os.fork() against JAX's thread pool is a deadlock hazard Python warns about explicitly.
# Keep this module JAX-free, and see regenerate_via_subprocess() for the pytest path.

_log = logging.getLogger(__name__)

HERE = Path(__file__).parent
SOURCE_M = HERE / "pitzer-kim functions.m"
GENERATED = HERE / "_generated"

MATLAB_BIN = "/Applications/MATLAB_R2026a.app/bin/matlab"

CACHE = {
    "oct2py": HERE / "oracle_octave.csv",
    "matlab": HERE / "oracle_matlab.csv",
}


# --- MATLAB source surgery -----------------------------------------------------------


def _scriptify(source: str) -> str:
    """Strip the `function` declaration and the trailing `end`, leaving a script.

    Deliberately mechanical: the body between them is copied byte for byte, so the oracle
    is the original file and not a transcription of it.
    """
    lines = source.splitlines()

    start = next(i for i, ln in enumerate(lines) if ln.lstrip().startswith("function"))
    end = max(i for i, ln in enumerate(lines) if ln.strip() == "end")
    if end <= start:
        raise ValueError("could not locate the function body in the MATLAB source")

    return "\n".join(lines[start + 1 : end]) + "\n"


def _write_generated() -> None:
    """Emit the script-ified body plus the driver that harvests the intermediates."""
    GENERATED.mkdir(exist_ok=True)

    (GENERATED / "pitzer_body.m").write_text(_scriptify(SOURCE_M.read_text()))

    # Built from TERM_NAMES so the column order of the oracle CSV is, by construction, the
    # field order of PitzerTerms. All 23 names exist verbatim as locals in the MATLAB.
    row = ", ".join(TERM_NAMES)
    n_terms = len(TERM_NAMES)

    # One script for both backends: it expects `in_csv` and `out_prefix` in the workspace.
    # fscanf is used rather than csvread/readmatrix because it is the one reader that
    # behaves identically in Octave and MATLAB.
    (GENERATED / "pitzer_parity_main.m").write_text(f"""\
% GENERATED by oracle.py — do not edit. Regenerate with `python oracle.py --regenerate`.
% Expects `in_csv` and `out_prefix` to already exist in the workspace.

fid = fopen(in_csv, 'r');
M = fscanf(fid, '%f,%f,%f\\n', [3 Inf])';
fclose(fid);

n = size(M, 1);
R = zeros(n, {n_terms});
for i = 1:n
    m_LiCl  = M(i, 1);
    m_NaCl  = M(i, 2);
    m_MgCl2 = M(i, 3);
    pitzer_body;                      % script: every local lands here
    R(i, :) = [{row}];
end

fid = fopen([out_prefix '_terms.csv'], 'w');
for i = 1:n
    fprintf(fid, '%.17g', R(i, 1));
    fprintf(fid, ',%.17g', R(i, 2:end));
    fprintf(fid, '\\n');
end
fclose(fid);

% J0/J1 on their own (spec sec.1). Running the body above left the handles in scope, so
% these are the same anonymous functions the model uses — not a second copy of them.
xs = XS_SWEEP;
fid = fopen([out_prefix '_j.csv'], 'w');
for k = 1:numel(xs)
    fprintf(fid, '%.17g,%.17g,%.17g\\n', xs(k), J0(xs(k)), J1(xs(k)));
end
fclose(fid);
""")


# --- backends ------------------------------------------------------------------------


def _run_oct2py(in_csv: Path, out_prefix: Path) -> None:
    from oct2py import Oct2Py

    with Oct2Py() as oc:
        oc.addpath(str(GENERATED))
        oc.push("in_csv", str(in_csv))
        oc.push("out_prefix", str(out_prefix))
        oc.push("XS_SWEEP", np.array(cases.X_SWEEP, dtype=np.float64))
        oc.eval("pitzer_parity_main", verbose=False)


def _run_matlab(in_csv: Path, out_prefix: Path) -> None:
    if not Path(MATLAB_BIN).exists():
        raise FileNotFoundError(f"MATLAB not found at {MATLAB_BIN}")

    xs = ", ".join(f"{x:.17g}" for x in cases.X_SWEEP)
    cmd = (
        f"addpath('{GENERATED}'); "
        f"in_csv = '{in_csv}'; out_prefix = '{out_prefix}'; "
        f"XS_SWEEP = [{xs}]; "
        f"pitzer_parity_main;"
    )
    proc = subprocess.run(
        [MATLAB_BIN, "-batch", cmd], capture_output=True, text=True, timeout=1800
    )
    if proc.returncode != 0:
        raise RuntimeError(f"matlab -batch failed:\n{proc.stdout}\n{proc.stderr}")


_BACKENDS = {"oct2py": _run_oct2py, "matlab": _run_matlab}


# --- public API ----------------------------------------------------------------------


def generate(backend: str = "oct2py") -> tuple[np.ndarray, np.ndarray]:
    """Run the oracle over the full input grid and return (terms, j_sweep).

    Returns
    -------
    terms : (n_cases, 23) float64
        Columns in TERM_NAMES order.
    j_sweep : (n_x, 3) float64
        Columns (X, J0, J1).
    """
    _write_generated()

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        in_csv = tmp / "inputs.csv"
        cases.write_inputs(in_csv, header=False)
        prefix = tmp / "out"

        _log.info("running %s oracle over %d cases", backend, len(cases.CASES))
        _BACKENDS[backend](in_csv, prefix)

        terms = np.loadtxt(prefix.with_name("out_terms.csv"), delimiter=",", ndmin=2)
        j_sweep = np.loadtxt(prefix.with_name("out_j.csv"), delimiter=",", ndmin=2)

    n = len(cases.CASES)
    if terms.shape != (n, len(TERM_NAMES)):
        raise ValueError(f"oracle returned {terms.shape}, expected {(n, len(TERM_NAMES))}")
    if j_sweep.shape != (len(cases.X_SWEEP), 3):
        raise ValueError(f"J sweep returned {j_sweep.shape}")

    return terms, j_sweep


def write_cache(backend: str = "oct2py") -> Path:
    """Run the oracle and write the golden CSV that the pytest suite reads."""
    terms, j_sweep = generate(backend)
    path = CACHE[backend]

    with open(path, "w") as fh:
        fh.write(f"# oracle backend: {backend}\n")
        fh.write("# generated by utils/pitzer_parity/oracle.py --regenerate; do not hand-edit\n")
        fh.write("kind,subgroup,m_LiCl,m_NaCl,m_MgCl2," + ",".join(TERM_NAMES) + "\n")

        for (group, a, b, c), row in zip(cases.CASES, terms):
            vals = ",".join(f"{v:.17g}" for v in row)
            fh.write(f"case,{group},{a:.17g},{b:.17g},{c:.17g},{vals}\n")

        pad = "," * (len(TERM_NAMES) - 2)
        for x, j0, j1 in j_sweep:
            fh.write(f"j,,{x:.17g},,,{j0:.17g},{j1:.17g}{pad}\n")

    _log.info("wrote %s", path)
    return path


def regenerate_via_subprocess(backend: str = "oct2py") -> tuple[np.ndarray, np.ndarray]:
    """Refresh the cache in a fresh interpreter, then load it.

    This is the entry point for the pytest `--regenerate-oracle` path. The test process has
    already imported utils.pitzer and therefore JAX, and oct2py talks to Octave over a
    forked pty — Python warns outright that os.fork() against JAX's thread pool is liable to
    deadlock. It does not reliably fail, which is worse than if it did. Spawning a clean
    interpreter sidesteps it entirely; the direct generate() call stays available for
    standalone use, where JAX was never loaded.
    """
    proc = subprocess.run(
        [sys.executable, str(Path(__file__).resolve()), "--regenerate", "--backend", backend],
        capture_output=True, text=True, timeout=1800,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"oracle regeneration failed:\n{proc.stdout}\n{proc.stderr}")
    return load_cache(backend)


def load_cache(backend: str = "oct2py") -> tuple[np.ndarray, np.ndarray]:
    """Read the committed golden CSV. Returns (terms, j_sweep), same shapes as generate()."""
    path = CACHE[backend]
    if not path.exists():
        raise FileNotFoundError(
            f"{path.name} is missing — run `python oracle.py --regenerate "
            f"--backend {backend}` (needs "
            f"{'GNU Octave' if backend == 'oct2py' else 'MATLAB'} installed)"
        )

    terms, j_rows = [], []
    with open(path) as fh:
        for line in fh:
            if line.startswith("#") or line.startswith("kind,"):
                continue
            parts = line.rstrip("\n").split(",")
            if parts[0] == "case":
                terms.append([float(v) for v in parts[5:]])
            elif parts[0] == "j":
                j_rows.append([float(parts[2]), float(parts[5]), float(parts[6])])

    return np.array(terms, dtype=np.float64), np.array(j_rows, dtype=np.float64)


def _cross_check() -> int:
    """Compare the two oracle backends against each other. Diagnostic, not a gate."""
    oct_terms, oct_j = load_cache("oct2py")
    mat_terms, mat_j = load_cache("matlab")

    print("J0/J1, Octave vs MATLAB:")
    print(f"{'X':>8} {'rel J0':>12} {'rel J1':>12}")
    for (x, o0, o1), (_, m0, m1) in zip(oct_j, mat_j):
        r0 = abs(o0 - m0) / max(abs(m0), 1e-300)
        r1 = abs(o1 - m1) / max(abs(m1), 1e-300)
        print(f"{x:8g} {r0:12.2e} {r1:12.2e}")

    print("\nWorst per-term relative disagreement across all cases:")
    worst = 0.0
    for j, name in enumerate(TERM_NAMES):
        o, m = oct_terms[:, j], mat_terms[:, j]
        both = np.isfinite(o) & np.isfinite(m)
        denom = np.maximum(np.abs(m[both]), 1e-300)
        rel = np.max(np.abs(o[both] - m[both]) / denom) if both.any() else 0.0
        worst = max(worst, rel)
        print(f"  {name:16s} {rel:.2e}")
    print(f"\nworst overall: {worst:.2e}")
    return 0


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    sys.path.insert(0, str(HERE))

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--regenerate", action="store_true", help="re-run the oracle")
    ap.add_argument("--backend", choices=list(_BACKENDS), default="oct2py")
    ap.add_argument("--cross-check", action="store_true",
                    help="compare the two cached backends against each other")
    ap.add_argument("--clean", action="store_true", help="remove _generated/")
    args = ap.parse_args()

    if args.clean:
        shutil.rmtree(GENERATED, ignore_errors=True)
    elif args.cross_check:
        raise SystemExit(_cross_check())
    elif args.regenerate:
        write_cache(args.backend)
    else:
        terms, j_sweep = load_cache(args.backend)
        print(f"{args.backend}: {terms.shape[0]} cases x {terms.shape[1]} terms, "
              f"{j_sweep.shape[0]} J-sweep points")
